### PR TITLE
Enable Close Icon on awesomeDialog

### PR DESCRIPTION
**Pull request by chenloong83**
A new key, showCloseIcon (by default false, i.e hide close icon).

If showCloseIcon set to true, close icon will show when awesomeDialog prompt. Dialog will be dismiss if close icon trigger.

Close icon is used in order to eliminate the crowd in buttons panel & developer can make use the limited buttons for other purposes, rather than just to close the dialog.

### CODE REVIEW

**Comment by marcos930807** [comment]
Hi @chenloong83 , I just checked the pr and the "x" to close the dialog is out of it, floating on top, did you do this with all intention? why not in the upper corner of the dialog??

**Comment by chenloong83** [comment]
Hi @marcos930807 , initially i put as per your recommendation. But personally feel the outcome is not very good (might due to i applied header, so overall results is weird), so i put the x as of right now.

x on the upper corner of the dialog is something like below
Capture

what you think?

**Comment by chenloong83** [comment]
Hi @marcos930807, i made the changes accordingly, can you help to review? Thank you!

**Comment by marcos930807** [comment]
Hi @chenloong83, Thanks for your support, I would like to be able to make a small modification in the way the dialog is closed and not use navigator.of (context) .pop directly, do you think you could activate "Allow edits from maintainers" to do so and then see if it complies with what you need. Thanks again.

**Comment by chenloong83** [comment]
Hi @marcos930807 yes, i had activated it, please proceed accordingly. Thanks!

**Comment by marcos930807** [comment]
Hi @chenloong83 sorry for delay de PR i now merged with a minors improves.

**Pull request merged**
